#
#                  newansi's Makefile
#
include ./cMakefile 
# to make anything, change directory to bin$ARCH and make it there
# see ./binsun4/Makefile
# and/or _Makefile for details
test_quartic test_lu test_macII test_macIIc add_to_this_list:
	cd $(bin) ; make $@
