liblayout: layout.h File Reference
layout.h File Reference
Layout function declarations and types.
#include <stddef.h>
#include <layout/types.h>
Typedefs
typedef struct lay_state * lay_statep
Pointer to the internal liblayout state.
Functions
void lay_optimize (lay_statep state)
Optimize the position of the input rectangles.
Initialization and setup functions
lay_statep lay_create_state ()
Create an internal state structure for use with subsequent liblayout functions.
void lay_destroy_state (lay_statep state)
Destroy an internal state structure.
int lay_verify_state (lay_statep state)
Assert that the internal state is consistent.
void lay_register_rects (lay_statep state, lay_coord_t *rect_pos, const ptrdiff_t pos_skip, lay_extent_t *rect_size, const ptrdiff_t size_skip, const int count)
Register the positions and sizes of a set of rectangles with liblayout.
Optimization settings
lay_real_t lay_get_overlap_weight (const lay_statep state)
Get the overlap penalty weight.
void lay_set_overlap_weight (lay_statep state, const lay_real_t weight)
Set the overlap penalty weight.
lay_real_t lay_get_edge_weight (const lay_statep state)
Get the edge penalty weight.
void lay_set_edge_weight (lay_statep state, const lay_real_t weight)
Set the edge penalty weight.
lay_real_t lay_get_center_weight (const lay_statep state)
Get the center penalty weight.
void lay_set_center_weight (lay_statep state, const lay_real_t weight)
Set the center penalty weight.
lay_real_t lay_get_orig_pos_weight (const lay_statep state)
Get the original position penalty weight.
void lay_set_orig_pos_weight (lay_statep state, const lay_real_t weight)
Set the original position penalty weight.
Detailed Description
Layout function declarations and types.
Typedef Documentation
typedef struct lay_state* lay_statep
Pointer to the internal liblayout state.
Function Documentation
lay_statep lay_create_state ()
Create an internal state structure for use with subsequent liblayout functions.
When finished, must be destroyed using lay_destroy_state().
References lay_state::center_weight, lay_state::dof, lay_state::edge_weight, lay_register_rects(), lay_verify_state(), lay_state::opt_args, lay_state::orig_pos_weight, and lay_state::overlap_weight.
void lay_destroy_state (lay_statep state)
Destroy an internal state structure.
lay_real_t lay_get_center_weight (const lay_statep state)
Get the center penalty weight.
References lay_state::center_weight.
lay_real_t lay_get_edge_weight (const lay_statep state)
Get the edge penalty weight.
References lay_state::edge_weight.
lay_real_t lay_get_orig_pos_weight (const lay_statep state)
Get the original position penalty weight.
References lay_state::orig_pos_weight.
lay_real_t lay_get_overlap_weight (const lay_statep state)
Get the overlap penalty weight.
References lay_state::overlap_weight.
void lay_optimize (lay_statep state)
Optimize the position of the input rectangles.
Overwrites the current positions with optimized positions.
References lay_state::dof, lay_verify_state(), lay_state::num_rects, and lay_state::opt_args.
void lay_register_rects (lay_statep state, lay_coord_t * rect_pos, const ptrdiff_t pos_skip, lay_extent_t * rect_size, const ptrdiff_t size_skip, const int count)
Register the positions and sizes of a set of rectangles with liblayout.
Parameters
state The internal state structure.
rect_pos A pointer to the x-coordinate of the first size. The y-coordinate of the first size is assumed to exist at *(rect_pos + 1). The pointer can be NULL, but no operations requiring sizes may be used.
pos_skip The number of bytes to add to rect_pos to get to the x-coordinate of the next size. If zero, then the data is assumed to be tightly packed, and pos_skip will be set to 2 * sizeof(lay_coord_t). Can be negative.
rect_size A pointer to the width of the first size. The height of the first size is assumed to exist at *(p + 1). The pointer can be NULL, but no operations requiring sizes may be used.
size_skip The number of bytes to add to p to get to the width of the next size. If zero, then the data is assumed to be tightly packed, and skip will be set to 2 * sizeof(lay_extent_t). Can be negative.
count The number of rectangles.
References lay_state::num_rects, lay_state::pos, lay_state::pos_skip, lay_state::size, and lay_state::size_skip.
Referenced by lay_create_state().
void lay_set_center_weight (lay_statep state, const lay_real_t weight)
Set the center penalty weight.
References lay_state::center_weight.
void lay_set_edge_weight (lay_statep state, const lay_real_t weight)
Set the edge penalty weight.
References lay_state::edge_weight.
void lay_set_orig_pos_weight (lay_statep state, const lay_real_t weight)
Set the original position penalty weight.
References lay_state::orig_pos_weight.
void lay_set_overlap_weight (lay_statep state, const lay_real_t weight)
Set the overlap penalty weight.
References lay_state::overlap_weight.
int lay_verify_state (lay_statep state)
Assert that the internal state is consistent.
References lay_state::num_rects, lay_state::pos_skip, and lay_state::size_skip.
Referenced by lay_create_state(), and lay_optimize().